name: Netflix
description: Discover a world of entertainment with Netflix, the ultimate streaming platform that brings your favorite TV shows, blockbuster movies, and exclusive original content right to your fingertips.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  video_player: ^2.7.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.1
  url_launcher: ^6.1.14
  html_unescape: ^2.0.0
  auto_size_text: ^3.0.0
  get: ^4.6.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/
    - assets/bottom_icons/
  
  fonts:
    - family: Wednesday
      fonts:
        - asset: fonts/Wednesday.ttf
          weight: 700
    - family: GoodTime
      fonts:
        - asset: fonts/GoodTime.otf
          weight: 700
    - family: NeuroPolX
      fonts:
        - asset: fonts/NeuroPolX.otf
          weight: 700